//-----------------------------------------------------------------------
// <copyright file="TypeOfNode.cs" company="Studio Arcade Ltd">
// Copyright © Studio Arcade Ltd 2012.
// All rights reserved.
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// This code is made available under the Ms-PL or GPL as appropriate.
// Please see LICENSE.txt for more details
// </copyright>
// <Author>Matt Lacey</Author>
//-----------------------------------------------------------------------

namespace NodeGardenLib
{
    /// <summary>
    /// The type of node - what it represents - how/why it was created
    /// </summary>
    public enum TypeOfNode
    {
        /// <summary>
        /// Node representing current device
        /// </summary>
        Self,

        /// <summary>
        /// Node generated by default on app start
        /// </summary>
        Default,

        /// <summary>
        /// Node representing another device
        /// </summary>
        Other
    }
}